services:
  - type: web
    name: site-jogo
    env: node
    plan: free
    buildCommand: npm install --no-audit --no-fund
    startCommand: npm start
    envVars:
      - key: COMMAND_SECRET
        value: carolina-hg
      - key: DEFAULT_CHANNEL
        value: icarolinaporto
      - key: ALLOWED_CHANNELS
        value: icarolinaporto
      - key: ALLOWED_USERS
        value: icarolinaporto,mod1,mod2
      - key: HG_ADULT_DEFAULT
        value: "0"
      - key: DATABASE_URL
        sync: false
      - key: TWITCH_CLIENT_ID
        sync: false
      - key: TWITCH_CLIENT_SECRET
        sync: false
      - key: HG_AUTO_INTERVAL_MS
        value: "5000"
      - key: HG_IGNORE_CHATTERS
        value: "streamelements,nightbot,moobot,streamlabs"
      - key: TWITCH_CHAT_TOKEN
        sync: false
      - key: TWITCH_CHAT_MODERATOR
        value: "icarolinaporto"
