services:
  - type: web
    name: site-ca-hunger-games-live
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: COMMAND_SECRET
        value: carolina-hg
      - key: DEFAULT_CHANNEL
        value: carolinaporto
      - key: ALLOWED_CHANNELS
        value: carolinaporto
      - key: ALLOWED_USERS
        value: carolinaporto,mod1,mod2
      - key: HG_MAX_PLAYERS
        value: "24"
      - key: HG_ADULT_DEFAULT
        value: "0"
      - key: DATABASE_URL
        sync: false
      - key: TWITCH_CLIENT_ID
        sync: false
      - key: TWITCH_CLIENT_SECRET
        sync: false
